splunk:
  conf:
    - key: web
      value:
        directory: /opt/splunk/etc/system/local
        content:
          settings:
            root_endpoint: /splunk
    - key: server
      value:
        directory: /opt/splunk/etc/system/local
        content:
          license:
            active_group: Free
