splunk:
  conf:
    - key: web
      value:
        directory: /opt/splunk/etc/system/local
        content:
          settings:
            root_endpoint: /splunk/web
    - key: server
      value:
        directory: /opt/splunk/etc/system/local
        content:
          general:
            allowRemoteLogin: always
          license:
            active_group: Free
